name: Deploy To VPS

on:
    push: 
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                
            - name: Deploy to server
              run: |
                curl -X POST "https://api.render.com/v1/services/${{secrets.RENDER_SERVICE_ID}}/deploys" \
                -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                -H "Accept: application/json" \
                -d '
                {
                  "clearCache": "clear"
                }
                '